// Code generated by mockery v1.0.0. DO NOT EDIT.

package mocks

import context "context"
import entities "github.com/minhluuquang/kilter/entities"

import mock "github.com/stretchr/testify/mock"

// Service is an autogenerated mock type for the Service type
type Service struct {
	mock.Mock
}

// FindByCategoriesAndLocation provides a mock function with given fields: ctx, categoryIDs, cityID
func (_m *Service) FindByCategoriesAndLocation(ctx context.Context, categoryIDs []string, cityID string) ([]entities.Gym, error) {
	ret := _m.Called(ctx, categoryIDs, cityID)

	var r0 []entities.Gym
	if rf, ok := ret.Get(0).(func(context.Context, []string, string) []entities.Gym); ok {
		r0 = rf(ctx, categoryIDs, cityID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]entities.Gym)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, []string, string) error); ok {
		r1 = rf(ctx, categoryIDs, cityID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
