// Code generated by mockery v1.0.0. DO NOT EDIT.

package mocks

import context "context"
import entities "github.com/minhluuquang/kilter/entities"
import mock "github.com/stretchr/testify/mock"

// Service is an autogenerated mock type for the Service type
type Service struct {
	mock.Mock
}

// AddList provides a mock function with given fields: ctx, userCategories
func (_m *Service) AddList(ctx context.Context, userCategories []entities.UsersCategory) error {
	ret := _m.Called(ctx, userCategories)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, []entities.UsersCategory) error); ok {
		r0 = rf(ctx, userCategories)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}
